[package]
name = "transfer-lamports"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "1.9.6"

[lib]
crate-type = ["cdylib","lib"]